---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: code-challenge
  name: backend-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: backend-app
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend-app
    spec:
      containers:
      - env:
          - name: DB
            value: 'postgresql://testuser:testuser123@test-postgres:5432/test_postgres'
        image: dockernvkk/nodejsapp:backend
        imagePullPolicy: IfNotPresent
        name: backend-app
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  namespace: code-challenge
  name: backend-app
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: backend-app