---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: code-challenge
  name: test-postgres
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: test-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test-postgres
    spec:
      containers:
      - env:
          - name: POSTGRES_DB
            value: 'test_postgres'
          - name: POSTGRES_USER
            value: 'testuser'
          - name: POSTGRES_PASSWORD
            value: 'testuser123'
        image: postgres
        imagePullPolicy: IfNotPresent
        name: test-postgres
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  namespace: code-challenge
  name: test-postgres
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: test-postgres